function value = isGeoTiff(proj)
%ISGEOTIFF True for a GeoTIFF projection structure.
%
%   VALUE = ISGEOTIFF(PROJ) returns 1 if PROJ contains GeoTIFF projection
%   fields, 0 otherwise.
%
%   See also ISMSTRUCT, ISVALIDPROJ.

%   Copyright 1996-2003 The MathWorks, Inc.

fieldNames = {'CornerCoords', ...
              'CTProjection', ...
              'Ellipsoid', ...
              'GeoTIFFCodes', ...
              'PM', ...
              'PMLongToGreenwich', ...
              'ProjParm', ...
              'SemiMajor', ...
              'SemiMinor', ...
              'Zone'};
value = isValidProj(proj, fieldNames);
