function checklatlon(lat, lon, func_name, ...
    lat_var_name, lon_var_name, lat_pos, lon_pos)
%CHECKLATLON Validate pair of latitude-longitude arrays
%
%     This function is intentionally undocumented and is intended for
%     use only by other Mapping Toolbox functions.  Its behavior may
%     change, or the function itself may be removed, in a future
%     release.
%
%   CHECKLATLON(LAT, LON, FUNC_NAME, LAT_VAR_NAME, LON_VAR_NAME,
%   LAT_POS, LON_POS) ensures that LAT and LON are real vectors or
%   arrays of matching size, having class 'double' or 'single', and that
%   for every NaN-valued element of LAT there is identically-positioned
%   NaN-valued element in LON, and vice versa.

% Copyright 2003-2017 The MathWorks, Inc.

% Real-valued double?
validateattributes( ...
    lat, {'double','single'} ,{'real'}, func_name, lat_var_name, lat_pos)
validateattributes( ...
    lon, {'double','single'} ,{'real'}, func_name, lon_var_name, lon_pos)

% Sizes match?
assert(isequal(size(lat),size(lon)), ...
    "map:" + func_name + ":latlonSizeMismatch", ...
    ['Function %s expected its %s and %s input arguments,\n', ...
    '%s and %s, to match in size.'], ...
    upper(func_name), num2ordinal(lat_pos), num2ordinal(lon_pos), ...
    lat_var_name, lon_var_name)

% NaN positions correspond?
assert(isequal(isnan(lat),isnan(lon)), ...
    "map:" + func_name + ":latlonNaNMismatch", ...
    ['Function %s expected its %s and %s input arguments,\n', ...
    '%s and %s, to have NaN-separators in corresponding positions.'], ...
    upper(func_name), num2ordinal(lat_pos), num2ordinal(lon_pos), ...
    lat_var_name, lon_var_name)
