function ax = initializeAxis(this,mapmodel,visibility)
%INITIALIZEAXIS Initialize axis to view the map.

%   Copyright 1996-2015 The MathWorks, Inc.

borderWidth = 2;
this.AxisPanel = uipanel( ...
    'Parent',this.Figure,...
    'Units','points',...
    'Position',getPanelPosition(this.Figure),...
    'BorderType','none',...
    'BorderWidth',borderWidth);

ax = map.graphics.internal.mapgraphics.Axes( ...
    'Parent',this.AxisPanel,...
    'Units','normalized','Position',[0 0 1 1],...
    'XTick',[],'YTick',[],'XColor','white','YColor','white',...
    'Visible',visibility);

ax.addModel(mapmodel);


function pixPanelPos = getPanelPosition(fig)
p = map.graphics.internal.getPositionInPoints(fig);

leftMargin = 10;
bottomMargin = 65;
topMargin = 10;
rightMargin = 10;

pixPanelPos = [leftMargin,bottomMargin,p(3)-leftMargin-rightMargin,...
               p(4) - bottomMargin - topMargin];
